name: StarFit tests (pytest)

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2.2.1
      with:
        python-version: "3.10"

    - name: Install gcc 11
      run: |
        sudo apt-get update
        gcc --version
        sudo apt install -y gcc-11
        sudo apt install -y gfortran-11
        gcc --version
        gcc-11 --version
        gfortran --version
        gfortran-11 --version
        which gfortran-11
        sudo update-alternatives --config gfortran
        gfortran --version

    - name: install starfit
      run: |
        ./download-data.sh
        pip install .[testing]

    - name: run pytest
      run: pytest
