name: StarFit tests (pytest)

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2.2.1
      with:
        python-version: "3.10"

    - name: Install gcc 12
      run: |
        sudo apt-get update
        gcc --version
        sudo apt install -y gcc-11
        gcc --version

    - name: install starfit
      run: |
        ./download-data.sh
        pip install .[testing]

    - name: run pytest
      run: pytest
