name: StarFit tests (pytest)

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2.2.1
      with:
        python-version: "3.10"

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64

    - name: install starfit
      run: |
        ./download-data.sh
        pip install .[testing]

    - name: run pytest
      run: pytest
